### PR TITLE
Write npm output

### PR DESCRIPTION
**Pull request by adriaanthomas**
As discussed in #17.

Unfortunately it is hard to write a test for this. I tried something like https://gist.github.com/pguillory/729616, but that does not catch `npm`'s output -- ideal would be to capture the child process's output, but that would be quite some work.

### CODE REVIEW

**Comment by vvo** [comment]
The current tests are passing which is a good start already! 

For tests, ave a look in spec/. But before that I have an idea to make it easier to test:

The programmatic interface could just get the stdio in a log function. For example it would be cool to be able to provide a log: function() {} in the programmatic interface.

And then on the command line the --show-npm-output would just mean "log: function() {console.log}".

This would have two advantages:
- make the cli programmatic interface better
- ease the mapping between the cli option and the programmatic interface
- ease the testing

Also, can you make sure the npm-pkgr command fails with exit code 1 when using --show-npm-output? This is very important. Add a test if feasible.

**Comment by adriaanthomas** [comment]
Sounds good to me, but:

1. how to map npm's output to `console.log`? Especially npm@3 does a lot more than just write lines. I would prefer to stay as close as possible to the normal npm output (with as little code as possible). OK if we just pass `process.stdout` and `process.stderr` instead (I don't think npm uses stdin)? So the API would accept any `Writable` stream.
2. Would you use this only for npm's output, or for all of npm-pkgr's messages? The latter makes more sense to me, but I'm just one user.

Of course the code would be a lot simpler if we just always show npm's output instead of making it an option, IMHO we could get away with not writing an extra test for that. If you want to hide npm's output you can always do so on the command line. Just my 2c.

I'll add a test for the exit code.

**Comment by vvo** [comment]
> how to map npm's output to console.log? Especially npm@3 does a lot more than just write lines. I would prefer to stay as close as possible to the normal npm output (with as little code as possible). OK if we just pass process.stdout and process.stderr instead (I don't think npm uses stdin)? So the API would accept any Writable stream.

Works for me, good point.

> Would you use this only for npm's output, or for all of npm-pkgr's messages? The latter makes more sense to me, but I'm just one user.

maybe name it npmLog, so that it's explicit what it does.

Then if at some point we need to programmatically get the npm-pkgr log we will, but right now it's not needed right?

> Of course the code would be a lot simpler if we just always show npm's output

I think I made npm-pkgr in a way it hides the npm output on purpose. I am ok providing an option to show it but not making it default.

**Comment by adriaanthomas** [comment]
Is there anything else that should be done here? I think it now works as discussed?

**Comment by vvo** [comment]
No, it's awesome. Merging and will release.

**Comment by adriaanthomas** [comment]
Thanks!

**Pull request merged**
