### PR TITLE
bump dependencies

### PR DESCRIPTION
**Pull request by Offirmo**
a small update. Seems it doesn't break anything.

### CODE REVIEW

**Comment by Offirmo** [comment]
.gitignore is the standard generated by Github

**Comment by vvo** [comment]
I will just give you push access here and on npm @Offirmo. No more using this (maybe in the future).

Still useful to you? If so, great!

**Comment by vvo** [comment]
Bumped to 0.2.1. Some tests are failing (concurrent test). We have a weird issue here but it's not linked to your PR. If you want to fix it, go for it. That's a concurrency fopen issue :D

**Comment by vvo** [comment]
> npm owner add offirmo
> + offirmo (npm-pkgr)

**Comment by Offirmo** [comment]
Is it really a test error or is it an expected error output during error testing ?

**Comment by vvo** [comment]
Seems like a test error, but the exit code is still good, weird

**Pull request merged**
