### PR TITLE
feat: add `prune` cli opt

### PR DESCRIPTION
**Pull request by iam4x**
wip, need the tests.

### CODE REVIEW

**Comment by vvo** [comment]
Looks awesome, let's test this, do you need help?

**Comment by iam4x** [comment]
Sorry for delay, I've written a little test, but I had to lower `nodejs` version to 4.2.1 LTS on travis since 5.0.0 has a lot of `fs` breaking changes and `mock-fs` don't support 5.0.0 (see https://github.com/tschaub/mock-fs/issues/67).

I hope it will fit your requirements :+1:

**Comment by vvo** [comment]
Very very good, just add the command to the readme and we are good for merge and release.

**Comment by iam4x** [comment]
Should be all good @vvo

**Comment by vvo** [comment]
Thanks a lot!

**Pull request merged**
